---
title: "YAML metadata for R Markdown with examples"
date: "`r Sys.Date()`"
output:
  md_document:
    toc: yes
  rmdformats::downcute:
    self_contained: no
  pdf_document:
    toc: yes
---


```{r setup, include=FALSE}
library(knitr)
library(rmdformats)

## Global options
options(max.print="75")
opts_chunk$set(echo=FALSE,
	             cache=TRUE,
               prompt=FALSE,
               tidy=TRUE,
               comment=NA,
               message=FALSE,
               warning=FALSE)
opts_knit$set(width=75)
```

# About the project

Rmd makes it possible to use a YAML header to specify certain parameters right at the beginning of the document. Built-in YAML parameters make it easier to create more organized and informative reports. However, there are few tutorials or summarized articles to display all the settings and parameters for `YAML metadata` in R Markdown. This readme file give you clear and enough materials for that.

# Useful websites

-   https://rmarkdown.rstudio.com/formats.html --- R Markdown formats from RStudio 
-   https://www.r-bloggers.com/2020/08/useful-yaml-options-for-generating-html-reports-in-r/ --- Useful YAML options for generating HTML reports in R

# useful tools

-   https://ymlthis.r-lib.org/index.html --- ymlthis: a package for writing YAML for R Markdown

-   https://github.com/kamapu/yamlme --- This package aims to save documents with their respective settings (yaml-head) in R-objects. 

# Terminology and norms

-   R lang -- use upper case letter `R`
-   Rmd -- capitalizes the first letter for `Rmd` files
-   R Markdown -- the R Markdown module or notebook of Rstudio 
-   rmarkdown -- the package of rmarkdown
-   YAML -- /ˈjæməl/ a recursive acronym for "YAML Ain't Markup Language"
-   YAML header/metadata -- the settings data written by YAML in Rmd header
-   All the YAML metadata are lower case letters except file paths or file names
